version: "3.3"

networks:
  appnet:
    external: true

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    environment:
      - "LINODE_TOKEN="
    networks:
      - appnet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./acme:/etc/traefik/acme
      - ./admins:/etc/traefik/admins:ro
    ports:
      - 80:80
      - 443:443
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`dash.dfg.rocks`)"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.myauth.basicauth.usersfile=/etc/traefik/admins"
      - "traefik.http.routers.traefik.middlewares=myauth"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.tls.certresolver=mydnschallenge"
      - "traefik.http.middlewares.traefik.redirectscheme.scheme=https"
