version: '3'

networks:
  appnet:
    external: true

services:
  tainer:
    image: portainer/portainer:latest
    command: -H unix:///var/run/docker.sock
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=host(`tainer.dfg.rocks`)"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
    networks:
      - appnet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/data:/data
