#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
	CREATE USER gitea;
	CREATE DATABASE gitea;
	GRANT ALL PRIVILEGES ON DATABASE gitea TO gitea;

	CREATE USER drone;
	CREATE DATABASE drone;
	GRANT ALL PRIVILEGES ON DATABASE drone TO drone;
EOSQL

